services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
  sidekiq:
    container_name: sidekiq
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis

    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  web:
    stdin_open: true
    tty: true
    container_name: discount-inss
    build: .
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
      bundle exec rake db:create &&
      bundle exec rake db:migrate &&
      bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/var/www/app
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
      - sidekiq

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  postgres: